/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/blog/",
  "headTags": [],
  "pages": [
    {
      "title": "Hello VuePress",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3ce32f6e",
      "path": "/"
    },
    {
      "title": "keqing",
      "frontmatter": {},
      "regularPath": "/views/genshin.html",
      "relativePath": "views/genshin.md",
      "key": "v-ce150180",
      "path": "/views/genshin.html",
      "headers": [
        {
          "level": 2,
          "title": "keqing",
          "slug": "keqing"
        }
      ]
    }
  ],
  "themeConfig": {
    "search": true,
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/guide/"
      },
      {
        "text": "External",
        "link": "https://google.com"
      }
    ]
  }
}